
services:
  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  indexer:
    container_name: indexer
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
  
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - API_PORT=${API_PORT}
    ports:
      - "127.0.0.1:${API_PORT}:${API_PORT}"
    depends_on:
      - db
      - indexer
